### ISSUE TITLE
Lack of retry-ability

### ISSUE THREAD

**Issue by nickbetsworth** [SMenigat/cypress-mailhog#11]
As per Cypress' ethos, failing commands will be retried until they pass, or a certain timeout is reached.

My tests that are using the mailhog library are currently flakey, as the mail can sometimes take half a second or so to arrive in the inbox. Is there any means of implementing 'retry-ability' similar to what Cypress has done for many of its commands?

**Comment by zettpunkt79** [comment]
Hi, this is just a workaround you can use by adding your own mailhog command with a little help of the [cypress-wait-until](https://github.com/NoriSte/cypress-wait-until) plugin:

```
Cypress.Commands.add('mhGetMailsBySender', (sender, wait=true) => {
  if(wait) {
    //Wait until there is at least one email from sender
    cy.waitUntil(() => cy.mhGetAllMails().then((mails) =>
      mails.filter((mail) => mail.Raw.From === sender).length > 0
    ), {
      errorMsg: `No emails found for ${sender}`,
      timeout: 5000,
      interval: 1000
    })
  }
  //Return all emails from sender
  cy.mhGetAllMails().then((mails) => {
    return mails.filter((mail) => mail.Raw.From === sender);
  })
})
```

**Comment by nickbetsworth** [comment]
I remember coming across cypress-wait-until plugin a while back and had considered combining the two.

Thanks for the code sample, I think I might take this approach for the time being :+1:
