### ISSUE TITLE
[Doubt] - I can't import "cypress-mailhog"

### ISSUE THREAD

**Issue by JoiceFelix** [SMenigat/cypress-mailhog#14]
Hi,

I am trying to use cypress-mailhog in my project.
I tried to follow the setup steps (in this [link](https://www.npmjs.com/package/cypress-mailhog)), but when I try to use any mh-cy command, I'm getting the same error: 
 ``Property 'mhGetAllMails' does not exist on type 'cy & EventEmitter'.ts(2339)``, see the image below.

![image](https://user-images.githubusercontent.com/73261356/98985788-d514bb00-2502-11eb-99d6-577e9649e043.png)

Just to has no doubts, I installed the cypress-mailhog into the projetc and added the import in cypress commands.js file.
Plz, see the images below.

[package,json]
![image](https://user-images.githubusercontent.com/73261356/98986576-dc889400-2503-11eb-88f3-f3dadab7c954.png)

[package-lock,json]
![image](https://user-images.githubusercontent.com/73261356/98986608-e7432900-2503-11eb-82af-bd392fe821b5.png)

[comands.js]
![image](https://user-images.githubusercontent.com/73261356/98986952-5751af00-2504-11eb-9460-1ad7318fcf68.png)

Could you help me to fix it? @SMenigat, @schugabe 

BR,

**Comment by SMenigat** [comment]
Hi there,

thank you for trying out my library 😊

It looks like you are implementing your cypress tests in TypeScript and not in JavaScript (your test file that you took the screenshot in has an `.ts` extension right?).

Sadly I do not have added type definitions for the custom "mh" helper functions yet.

I would suggest you just implement the tests in JavaScript in the meantime (maybe renaming your test file from `.ts` to `.js` is already enough).

Optionally you could also [add the missing types following the guide here](https://docs.cypress.io/guides/tooling/typescript-support.html#Types-for-custom-commands).

I would appreciate an PR adding the types if you have the time 😉

**Comment by JoiceFelix** [comment]
Thank you @SMenigat.

I will try to add the missing types and contribute to the project asap.
