### ISSUE TITLE
How to authenticate requests?

### ISSUE THREAD

**Issue by ZathrasXI** [SMenigat/cypress-mailhog#24]
I am using cypress and mailhog to test the email validation step of the sign up process on our staging site. Currently, the test is failing with a 401 status code - the mailhog inbox requires a username and password.

How can I pass a username and password into the API request?

**Comment by preetibellad** [comment]
I am also facing the same issue in my Cypress tests run on CI.

**Comment by preetibellad** [comment]
@ZathrasXI ... This got resolved for me when I updated mailhog Url in config file as 
https://<username>:<password>@mailhogUrl

**Comment by ZathrasXI** [comment]
Thank you @preetibellad for sharing that with me. I will remember do that next time I need it.

**Comment by SMenigat** [comment]
BASIC Auth Support was just added with #32. 
You should be able to update the package on your end and try it out 👍🏻
