### ISSUE TITLE
Parsing of json result fails

### ISSUE THREAD

**Issue by schugabe** [SMenigat/cypress-mailhog#3]
With cypress 3.7 all mailhog calls fail since JSON.parse is called for the already decoded result. It seems that cy.request changed.

I subbmited a PR #2 that fixes this issue.

**Comment by SMenigat** [comment]
Thanks for reporting and resolving the issue. Fix is merged and the package is updated :+1:

**Comment by schugabe** [comment]
Thank you for the fast release :+1:
