### ISSUE TITLE
Mailhog timeout 9999 limit

### ISSUE THREAD

**Issue by gabalicious** [SMenigat/cypress-mailhog#30]
So it would be awesome if you can somehow make limit be a config option or an optional parameter for some/all of the methods.

My tests timeout because `/api/v2/messages?limit=9999` just takes too long.  When I tested in a browser the same behavior was prevalent. But when I changed the limit to 100 or 10 it worked for me.

**Comment by SMenigat** [comment]
Hi Justin, this was just implemented with #32. 
You should be able to update the package on your end and try it out 👍🏻
