### ISSUE TITLE
Support cypress ^10.0.0

### ISSUE THREAD

**Issue by Pashozator** [SMenigat/cypress-mailhog#34]
In cypress 10.0.0 cypress.json file is no longer supported.

> Using a cypress.json configuration file is no longer supported. Replace this configuration file with a cypress.config.js, cypress.config.ts, cypress.config.cjs or cypress.config.mjs file. This change provides better flexibility and extensibility of configuration. An error will be thrown if both a cypress.json file and cypress.config.{cjs,js,mjs,ts} file are found. Addressed in [#18221](https://github.com/cypress-io/cypress/pull/18221), [#18300](https://github.com/cypress-io/cypress/pull/18300), [#20554](https://github.com/cypress-io/cypress/pull/20554), and [#20643](https://github.com/cypress-io/cypress/pull/20643).

We should use cypress env to provide `mailHogUrl`.

**Comment by juancarlosjr97** [comment]
Workaround while this is gets merged

Add to the `cypress.config.ts`

```ts
import { defineConfig } from "cypress";

export default defineConfig({
  projectId: "****",
  e2e: {
    // Workaround until https://github.com/SMenigat/cypress-mailhog/issues/34 gets merged and the configuration of cypress-mailhog moves as an environmental variable
    // @ts-ignore
    mailHogUrl: "http://localhost:8025/",
    setupNodeEvents() {},
  },
  component: {
    devServer: {
      framework: "next",
      bundler: "webpack",
    },
  },
});

```

**Comment by SMenigat** [comment]
Hi @juancarlosjr97 , 

thanks for your participation and using this package. 
You would not need to hack this in via the `e2e` config with `@ts-ignore` by using the [default env config](https://docs.cypress.io/guides/references/configuration#Global). 

Something like this should work: 

 ```javascript
export default defineConfig({
  // ...
  env: {
    mailHogUrl: "http://localhost:8025/",
  },
  // ...
});
```

Configuring the `mailHogUrl` via ENV variables was always the preferred way of doing it, it was just never documented. Additionally old cypress versions didnt have feature for "default env values" yet, so using the config for defining a default for localhost was the actual workaround. 

@Pashozator was so kind to adjust the documentation accordingly here in #35 which we soon should be able to merge.

**Comment by juancarlosjr97** [comment]
Thank you @SMenigat!
