### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by juliangeissler** [SMenigat/cypress-mailhog#41]
Hi,

we like your library! But your license is prevent us from using it

Would it be possible that you switch the license to MIT?

Thanks

**Comment by SMenigat** [comment]
Hi Julian, 

thanks for your request. Yes having it on GPL-2 made no sense, sorry for not changing that earlier. 
Just changed it and released it accordingly. 

If you like the library I would be very happy about a ⭐ . 

Have a nice day 👋🏻
